version: "3.4"
services:
  local-stack:
    image: local-stack
    build:
      context: .
      dockerfile: LocalStackDockerfile

  aws-cli:
    image: aws-cli
    build:
      context: .
      dockerfile: AwsCliDockerfile

  postgre-sql:
    image: postgre-sql
    build:
      context: .
      dockerfile: PostgrDockerfile
    ports:
      - "5432:5432"
