version: '3.4'

services:
  afshin-local-stack:
    container_name: afshin-local-stack-container-light
    image: afshin-local-stack
    ports:
      - "4566-4599:4566-4599"
      - "8000-8080:8000-8080"
    environment:
      AWS_ACCESS_KEY_ID: "1234"
      AWS_SECRET_ACCESS_KEY: "1234"
      AWS_DEFAULT_REGION: "ap-southeast-2"
      SERVICES: "sqs,sns,s3"
      HOSTNAME: "at-local-stack"
      HOSTNAME_EXTERNAL: "at-local-stack"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /tmp/localstack:exec,mode=600

  aws-cli:
    image: afshin-aws-cli
    depends_on:
      - afshin-local-stack
    tty: true
